Documents/rails_projects/simulador/config/routes.rb
SampleApp::Application.routes.draw do
  resources :fees, only: [:show]
  resources :users do 
    resources :credits do
      resources :fees
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :credit_lines
  root  'static_pages#home'
  match '/createcreditline', to: 'credit_lines#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

Documents/rails_projects/simulador/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    SimuladoresDeCredito.com  by Juan Pablo Reyes G
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de nosotros",   about_path %></li>
    </ul>
  </nav>
</footer>

Documents/rails_projects/simulador/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SimuladoresDeCredito.com", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Ayuda", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Mi Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Cerrar Sesion", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Iniciar Sesion", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

Documents/rails_projects/simulador/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

Documents/rails_projects/simulador/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <p>
      <p>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>