Documents/rails_projects/simulador/config/routes.rb
SampleApp::Application.routes.draw do
  resources :fees, only: [:show]
  resources :users do 
    resources :credits do
      resources :fees
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :credit_lines
  root  'static_pages#home'
  match '/createcreditline', to: 'credit_lines#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

Documents/rails_projects/simulador/app/models/credit.rb
class Credit < ActiveRecord::Base
	belongs_to :user
	has_many :fees, dependent: :destroy
	validates :cedula, presence: true
	validates :valorCredito, presence: true
	validates :plazo, presence: true
	validates :user_id, presence: true
	validates :lineaCredito, presence: true


	def generarPlanes
		
		#credits = Credit.where(estado: "En proceso")
#
#		t1 = Time.now
#		threads = []
#
#		
#		credits.each do 
#			threads << Thread.new do
#				calcularRiesgo
#			end
#		end
#
#		threads.each do |t|
#			t.join
#		end
#
#
#			
#		credits.each do |credit| 		
#				procesarCredito(credit)
#				credit.estado = ("Generado")
#				credit.nivelRiesgo = rand(10) + 1
#				credit.save
#		
#
##		puts "Cron executed in #{Time.now - t1}"

		
		calcularRiesgo
		procesarCredito
		self.estado = ("Generado")
				self.nivelRiesgo = rand(10) + 1
				self.save
	
	end	

			
		
		

	def calcularRiesgo()
		timeStart = Time.now
		timeEnd = timeStart

		num = 1
		while timeEnd - timeStart <= 25 do
			timeEnd = Time.now
			
			i = 2
			while i <= num do
				if num % i == 0
					break
				end
				i += 1
			end

			num =+ 1

		end

	
	end


	def procesarCredito()

		i = 0
			fee = nil

			monthRate = self.user.credit_lines.find(self.lineaCredito).annualRate / 1200
			feeNumber = (self.plazo).to_d
			creditValue = (self.valorCredito).to_d
			saldoPendiente = creditValue
			
			feeAmount = (creditValue * monthRate * (1 + monthRate ) ** feeNumber) / 
													(((1 + monthRate ) ** feeNumber)  - 1)
	

				until i >= self.plazo do
			

					fee = self.fees.build

							
					fee.valor_cuota =	(feeAmount.round(2)).to_s		
					fee.numero_cuota = i + 1
					fee.amortizacion = ((feeAmount - creditValue*monthRate)*(1 + monthRate)**i).round(2).to_s
					fee.pago_intereses = (feeAmount - fee.amortizacion.to_d).round(2).to_s
					
					saldoPendiente = saldoPendiente - fee.amortizacion.to_d
					fee.saldo_pendiente = saldoPendiente.to_s
					#fee.saldo_pendiente = (creditValue - feeAmount.to_i*(i+1)).to_s		

					fee.save
									#fee.update_attribute( :valor_couta, feeAmount.to_s)

					i += 1
				end

	
	end


	def self.clean
		Credit.all.each do |credit|
			credit.estado = "En proceso"
			credit.nivelRiesgo = "En proceso"
			credit.save
			credit.fees.all.each do |n|
				n.delete
			end
		end

	end

	
	

end

Documents/rails_projects/simulador/app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  skip_before_filter:verify_authenticity_token


def new
    @credit = owner_user.credits.build
end

def index
  owner_user
  if params[:cedula]
    @cedula = params[:cedula]
    @credits = owner_user.credits.find( :all, :conditions => ["cedula = ?", params[:cedula] ] ).paginate(page: params[:page], per_page: 50)
  else
    @cedula = nil
  end

end

def create
  	@credit = owner_user.credits.build(credit_params)
  	if @credit.save
  		flash[:success] = "Nuevo credito creado"
      @credit.delay(:queue => 'default').generarPlanes
  		redirect_to user_credits_path( params[:user_id] )
  	else
  		render 'new'
  	end
end

private

  def owner_user
  	@owner_user  = User.find( params[:user_id] )
  end

  def credit_line
    @credit_line = Credit_line.find( params[:credit_line_id])
  end


def credit_params
      params.require(:credit).permit(:cedula, :valorCredito, :plazo, :lineaCredito)
end


end

Documents/rails_projects/simulador/app/views/credits/_credit.html.erb
<tr>
  <td style="text-align:left;"><%= credit.cedula %> </td>
  <td style="text-align:left;"><%= credit.valorCredito %></td>
  <td style="text-align:left;"><%= credit.plazo %></td>
  <td style="text-align:left;"><%= credit.user.credit_lines.find(credit.lineaCredito).name %></td>

  <td style="text-align:left;">
  	<%= credit.estado %> 
  	<%if credit.estado == "Generado"%>
  	<%= link_to "Ver detalles", user_credit_fees_path( params[:id] || params[:user_id], credit.id) %>
  	<% end%>
  </td>
  <td style="text-align:left;"><%= credit.nivelRiesgo %></td>
  <td style="text-align:left;"><%= credit.created_at %></td>


</tr>

Documents/rails_projects/simulador/app/views/credits/index.html.erb
<% provide(:title, 'Pagina de creditos con ' + @owner_user.pyme) %>

<h1>Creditos con <%= @owner_user.pyme %></h1>

<h2>Revise el estado de sus creditos</h2>


<div class="row">
  <div class="span6 offset3">
 <%= form_tag(user_credits_path( params[:user_id]), method: "get") do |f| %>
	 <%= label_tag(:cedula, "Cedula:") %>
  	 <%= text_field_tag(:cedula) %>
  	 <center>
	<%= submit_tag "Revisar", class: "btn btn-large btn-primary" %>
</center>
<% end %>
  </div>
</div>

<%if @cedula.nil? || @cedula.empty? || @credits.empty?%>

<%else %>
<center>
<table border=1>
	  <tr>
    <th style="text-align:center;">Cedula</th>
    <th style="text-align:center;">Valor Credito</th>
    <th style="text-align:center;">Plazo</th>
    <th style="text-align:center;">Linea de Credito</th>
    <th style="text-align:center;">Estado</th>
    <th style="text-align:center;">Nivel de Riesgo</th>
    <th style="text-align:center;">Fecha creacion</th>
  </tr>
	  <ol class="credit_lines">
      <%= render @credits %>
      </ol>
      <%= will_paginate @credits %>
  </table>
</center>

<%end%>

<hr>

<h2>Solicite un nuevo credito</h2>


 <%= form_tag(new_user_credit_path( params[:user_id] ), method: "get") do |f| %>
  	 <center>
	<%= submit_tag "Nuevo Credito", class: "btn btn-large btn-primary" %>
</center>
<% end %>

Documents/rails_projects/simulador/app/views/credits/new.html.erb
<% provide(:title, 'Aplicacion a un nuevo credito ' + @owner_user.pyme) %>
<h1>Aplicacion a un nuevo credito con <%= @owner_user.pyme %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for [@owner_user, @credit] do |f| %>
  	  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :cedula %>
      <%= f.text_field :cedula %>

      <%= f.label :valor_credito %>
      <%= f.text_field :valorCredito %>

      <%= f.label :plazo %>
      <%= f.text_field :plazo %>

      <%= f.label :linea_de_Credito %>
      <%= f.collection_select :lineaCredito, @owner_user.credit_lines.all, :id, :name %>


      <%= f.submit "Solicitar credito", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>