Documents/rails_projects/simulador/config/routes.rb
SampleApp::Application.routes.draw do
  resources :fees, only: [:show]
  resources :users do 
    resources :credits do
      resources :fees
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :credit_lines
  root  'static_pages#home'
  match '/createcreditline', to: 'credit_lines#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

Documents/rails_projects/simulador/app/models/credit_line.rb
class CreditLine < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :name, presence: true
	validates :annualRate, presence: true
end

Documents/rails_projects/simulador/app/controllers/credit_lines_controller.rb
class CreditLinesController < ApplicationController
  before_action :signed_in_user , only: [:create, :edit, :destroy]
  before_action :correct_user, only: [:edit, :destroy]


  def new
    @credit_line = current_user.credit_lines.build if signed_in?
  end
  def create
  	@credit_line = current_user.credit_lines.build(credit_line_params)
  	if @credit_line.save
  		flash[:success] = "Nueva linea de credito creada"
  		redirect_to current_user
  	else
  		render 'new'
  	end
  end

  def edit
    @credit_line = current_user.credit_lines.find(params[:id])
  end

  def update
    @credit_line = current_user.credit_lines.find(params[:id])
    if @credit_line.update_attributes(credit_line_params)
      flash[:success] = "Linea de credito actualizada"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def destroy
    @credits = current_user.credits.find( :all, :conditions => ["lineaCredito = ?", @credit_line.id])
    @credits.each do |credit|
      credit.destroy
    end

    @credit_line.destroy
    flash[:success] = "Linea de credito eliminada con exito"
    redirect_to current_user
  end


  private

  	def credit_line_params
  		params.require(:credit_line).permit(:name, :annualRate)
  	end

    def correct_user
      @credit_line = current_user.credit_lines.find_by(id: params[:id])
      redirect_to root_url if @credit_line.nil?
    end

end

Documents/rails_projects/simulador/app/views/credit_lines/_credit_line.html.erb
<li>
  <span class="name"><%= credit_line.name %></span>
  <span class="annual_rate"><%= credit_line.annualRate %> %
  <% if current_user?(credit_line.user)%>
   | <%= link_to "editar", edit_credit_line_path(credit_line.id) %>
   | <%= link_to "borrar", credit_line, method: :delete,
                                  data: { confirm: "Esta seguro?" } %>
  <% end %>
  </span>
</li>

Documents/rails_projects/simulador/app/views/credit_lines/edit.html.erb
<% provide(:title, "Editar Linea de Credito") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@credit_line) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :annual_Rate %>
      <%= f.text_field :annualRate %>

      <%= f.submit "Guardar cambios", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

Documents/rails_projects/simulador/app/views/credit_lines/new.html.erb
<% provide(:title, 'Crear linea de credito') %>
<h1>Creacion de nueva Linea de Credito</h1>

<div class="row">
  <div class="span6 offset3">



    <%= form_for(@credit_line) do |f| %>
  	  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :annual_Rate %>
      <%= f.text_field :annualRate %>

      <%= f.submit "Crear linea de credito", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>