Documents/rails_projects/simulador/config/routes.rb
SampleApp::Application.routes.draw do
  resources :fees, only: [:show]
  resources :users do 
    resources :credits do
      resources :fees
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :credit_lines
  root  'static_pages#home'
  match '/createcreditline', to: 'credit_lines#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

Documents/rails_projects/simulador/app/models/user.rb
class User < ActiveRecord::Base
  has_many :credit_lines, dependent: :destroy
  has_many :credits, dependent: :destroy
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}, 
					uniqueness: { case_sensitive: false }
  validates :pyme, presence: true, length: { maximum: 50 }
	has_secure_password
	validates :password, length: { minimum:6 }

 def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
  end

end

Documents/rails_projects/simulador/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuario borrado."
    redirect_to users_url
  end

	def show
		@user = User.find(params[:id])
    @credit_lines = @user.credit_lines.paginate(page: params[:page])
    @credits = @user.credits.paginate(page: params[:page])
	end

  def new
    @user = User.new
  end
 def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
    	flash[:success] = "Bienvenido a SimuladoresDeCredito.com"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

   def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil actualizado"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :pyme, :password, 
                                   :password_confirmation)
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to @user unless current_user?(@user)
    end

    def admin_user
      redirect to @user unless current_user.admin?
    end


    


end

Documents/rails_projects/simulador/app/helpers/users_helper.rb
module UsersHelper

	 # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

Documents/rails_projects/simulador/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

Documents/rails_projects/simulador/app/views/users/edit.html.erb
<% provide(:title, "Editar perfil") %>
<h1>Actualice su perfil</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :nombre %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :contrasena %>
      <%= f.password_field :password %>

      <%= f.label :confirmation_contrasena, "Confirmar contrasena" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

Documents/rails_projects/simulador/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

Documents/rails_projects/simulador/app/views/users/new.html.erb
<% provide(:title, 'Crear mi cuenta') %>
<h1>Crear mi cuenta</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
  	  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :nombre %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :pyme %>
      <%= f.text_field :pyme %>

      <%= f.label :contrasena %>
      <%= f.password_field :password %>

      <%= f.label :confirmar_contrasena, "Confirmacion" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Crear mi cuenta", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

Documents/rails_projects/simulador/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span10 offset3">
      <center><p>La URL de <%=@user.pyme %> para solicitar creditos: <%=link_to user_credits_url(@user.id).to_s, user_credits_path(@user.id) %> </p></center>
    </div>

<center>
  <div class="span8 offset3">



&nbsp;
&nbsp;
&nbsp;

    <% if @user.credit_lines.any? %>
      <h3>Lineas de Credito </h3>
      <ol class="credit_lines">
        <%= render @credit_lines %>
      </ol>
      <%= will_paginate @credit_lines %>
    <% end %>
      <%= link_to "Nueva linea de credito", createcreditline_path, class: "btn btn-large btn-primary" %>
  </div>
</center>

&nbsp;
&nbsp;
&nbsp;


    <% if @user.credits.any? %>
    <center>
<table border=1>
    <tr>
    <th style="text-align:center;">Cedula</th>
    <th style="text-align:center;">Valor Credito</th>
    <th style="text-align:center;">Plazo</th>
    <th style="text-align:center;">Linea de Credito</th>
    <th style="text-align:center;">Estado</th>
    <th style="text-align:center;">Nivel de Riesgo</th>
    <th style="text-align:center;">Fecha creacion</th>
  </tr>
      <h3>Creditos solicitados por clientes (<%= @user.credits.count %>)</h3>
      <ol class="credits">
        <%= render @credits %>
      </ol>
      <%= will_paginate @credits %>
        </table>
    <% end %>


</div>

</div>